### PR TITLE
🤖🚨  4 changes in existing fixtures detected

### PR DESCRIPTION
**Pull request by octokit-fixture-user-a**
Dearest humans,

My friend Travis asked me to let you know that they found API changes in their daily routine check.

### CODE REVIEW

**Comment by gr2m** [comment]
@kytrinyx do you know what this new `"x-now-region"` header is? The test run on travis, it’s persistent when I restart the build. But I cannot recreate it locally

**Comment by kytrinyx** [comment]
I've no idea, but I'm asking around. I'll report back what I find out.

**Comment by kytrinyx** [comment]
This isn't a header that GitHub sets. Do you know if Travis is using a proxy? (Do you know any Travis folks? If not I can ask someone there)

**Comment by kytrinyx** [comment]
If you restart the build is it using... cached fixtures?

**Comment by gr2m** [comment]
Oh my, I know what it is now. I’ve setup a proxy because unauthenticated requests would all get directly blocked by GitHub, see https://github.com/gr2m/octokit-fixtures/issues/3

And now it makes sense that I can’t reproduce it on the client, too. The proxy is running on [now](https://zeit.co/now), so the header name makes perfectly sense now as well. I’m so sorry for the noise 😥

> If you restart the build is it using... cached fixtures?

Yes, it has all fixtures from previous recording stored in https://github.com/gr2m/octokit-fixtures/tree/master/fixtures/api.github.com. And it compares these to the new recordings in a daily Travis Cron job. If it finds any differences, it will create a pull request like this one.

**Comment by kytrinyx** [comment]
Yay! Glad that's sorted :)

> I’m so sorry for the noise

Not at all. This stuff is totally confusing. Definitely worth raising the question. ✨

**Pull request closed without merging**
